# Generated by Django 5.0.7 on 2024-09-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=0)),
                ('block_size', models.IntegerField(default=1)),
                ('data', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BlockHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TextField()),
                ('version', models.TextField(default='01000000')),
                ('bits', models.TextField(default='00000000')),
                ('nonce', models.TextField(default='00000000')),
                ('previous_hash', models.TextField(default='0000000000000000000000000000000000000000000000000000000000000000')),
                ('block_hash', models.TextField(default='0000000000000000000000000000000000000000000000000000000000000000')),
                ('merkle_root', models.TextField(default='0000000000000000000000000000000000000000000000000000000000000000')),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Blockchain', max_length=255)),
                ('chain', models.ManyToManyField(to='api.block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='block_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blockheader'),
        ),
    ]
