# Generated by Django 5.0.7 on 2025-01-01 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Blockchain', max_length=255, unique=True)),
                ('target', models.CharField(default='0', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlockHeader',
            fields=[
                ('timestamp', models.IntegerField(null=True)),
                ('version', models.TextField(default='01000000')),
                ('bits', models.TextField(default='00000000')),
                ('nonce', models.TextField(default='00000000')),
                ('previous_hash', models.TextField(default='0000000000000000000000000000000000000000000000000000000000000000')),
                ('merkle_root', models.TextField(default='0000000000000000000000000000000000000000000000000000000000000000')),
                ('block_hash', models.TextField(default='0000000000000000000000000000000000000000000000000000000000000000', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField(db_index=True, default=0)),
                ('size', models.IntegerField(default=0)),
                ('data', models.TextField(default='')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blockchain')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blockheader')),
            ],
        ),
    ]
