# Generated by Django 5.0.7 on 2024-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockheader',
            name='id',
        ),
        migrations.AlterField(
            model_name='blockheader',
            name='block_hash',
            field=models.TextField(default='0000000000000000000000000000000000000000000000000000000000000000', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blockheader',
            name='timestamp',
            field=models.IntegerField(default=1726827752),
        ),
    ]
